#!/bin/sh
#
# @name Kolibri
#
# @type Tilting Multirotor
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
#
# @output AUX1 servo 1
# @output AUX2 servo 2
# @output AUX3 servo 3
# @output AUX4 servo 4
# @output AUX5 servo 5
# @output AUX6 servo 6
#
# @maintainer Yang Li <yangli052903@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults


param set-default MAV_TYPE 14

param set-default SYS_CTRL_ALLOC 1 # dynamic allocation
param set-default CA_AIRFRAME 11   # Tilting Multirotor
param set-default CA_TILTING_TYPE 1 # Omnidirectional tilting drone

# Hexacopter: 6 rotors placed at vertices of a regular hexagon
# Each arm length = 0.5 m (50 cm) and is actuated by an independent servo

# Set all 6 main channels and 6 aux (servos)
set PWM_OUT 123456
set PWM_AUX_OUT 123456
param set-default CA_ROTOR_COUNT 6
param set-default CA_SV_TL_COUNT 6

# Rotor positions (meters) around center (regular hexagon), starting at 0° and going CCW:
# 0°:  ( 0.500,  0.000)
# 60°: ( 0.250,  0.433)
#120°: (-0.250,  0.433)
#180°: (-0.500,  0.000)
#240°: (-0.250, -0.433)
#300°: ( 0.250, -0.433)
# All rotors mounted roughly in the same plane: PZ = 0.00

param set-default CA_ROTOR0_PX 0.500  # M1 (0°)
param set-default CA_ROTOR0_PY 0.000
param set-default CA_ROTOR0_PZ 0.00
param set-default CA_ROTOR0_KM -0.05  # M1 CW

param set-default CA_ROTOR1_PX 0.250  # M2 (60°)
param set-default CA_ROTOR1_PY 0.433
param set-default CA_ROTOR1_PZ 0.00
param set-default CA_ROTOR1_KM 0.05   # M2 CCW

param set-default CA_ROTOR2_PX -0.250 # M3 (120°)
param set-default CA_ROTOR2_PY 0.433
param set-default CA_ROTOR2_PZ 0.00
param set-default CA_ROTOR2_KM -0.05  # M3 CW

param set-default CA_ROTOR3_PX -0.500 # M4 (180°)
param set-default CA_ROTOR3_PY 0.000
param set-default CA_ROTOR3_PZ 0.00
param set-default CA_ROTOR3_KM 0.05   # M4 CCW

param set-default CA_ROTOR4_PX -0.250 # M5 (240°)
param set-default CA_ROTOR4_PY -0.433
param set-default CA_ROTOR4_PZ 0.00
param set-default CA_ROTOR4_KM -0.05  # M5 CW

param set-default CA_ROTOR5_PX 0.250  # M6 (300°)
param set-default CA_ROTOR5_PY -0.433
param set-default CA_ROTOR5_PZ 0.00
param set-default CA_ROTOR5_KM 0.05   # M6 CCW

param set-default PWM_MAIN_FUNC1 101 #esc
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 201 #servo
param set-default PWM_MAIN_FUNC8 202
param set-default PWM_MAIN_FUNC9 203
param set-default PWM_MAIN_FUNC10 204
param set-default PWM_MAIN_FUNC11 205
param set-default PWM_MAIN_FUNC12 206

# Limits for tilting angles
param set-default CA_SV_TL0_MAXA 30
param set-default CA_SV_TL0_MINA -30
param set-default CA_SV_TL1_MAXA 30
param set-default CA_SV_TL1_MINA -30
param set-default CA_SV_TL2_MAXA 30
param set-default CA_SV_TL2_MINA -30
param set-default CA_SV_TL3_MAXA 30
param set-default CA_SV_TL3_MINA -30